/*
World Mining Commodities Project Overview
This project is a comprehensive SQL-based analysis of the mining industry ideal for baginners
and intermediate learners.
This project is centered around analyzing them mining industry using real-world dataset from the
World Mining Commodities dataset repository. It involoes exploring the mining companies, their operaitonal
data, and country-level mining statistics to generate insights and develop SQL proficiency.

*/

-- Create Database named World_Mining
Create Database World_Mining;

-- Importing First Table into the database
SELECT 
    *
FROM
    116_world_mining_companies_clean;

-- Importing second table into the database
SELECT 
    *
FROM
    world_mining_commodities_clean;


-- chaning name of the table
Alter table 116_world_mining_companies_clean
Rename To table_1;

Alter Table world_mining_commodities_clean
Rename To table_2;


-- Renaming column names from table_2
ALTER TABLE table_2
RENAME COLUMN `2018` TO `year_2018`;

ALTER TABLE table_2
RENAME COLUMN `2019` TO `year_2019`;

ALTER TABLE table_2
RENAME COLUMN `2020` TO `year_2020`;

ALTER TABLE table_2
RENAME COLUMN `2021` TO `year_2021`;

ALTER TABLE table_2
RENAME COLUMN `2022` TO `year_2022`;

Select * From table_1;
Select * from table_2;

-- Basic Queries
-- 1. List all unique commodities mined by companies in Table 1.
SELECT DISTINCT
    Commodity
FROM
    table_1;


-- 2. Retrieve the names and websites of all companies operating in Canada.
SELECT 
    Name, Website
FROM
    table_1
WHERE
    Location LIKE '%Canada%';

-- 3. List the countries from Table 2 where 'Gold' was mined in 2022.
SELECT 
    country
FROM
    Table_2
WHERE
    mined_raw_mat LIKE '%Gold%'
        AND year_2022 > 0;

-- 4. Find the total production of 'Copper' for the year 2020 across all countries
SELECT 
    SUM(year_2020) AS total_Copper_Production
FROM
    table_2
WHERE
    mined_raw_mat = 'Copper';

-- 5. Display the name and project stage of companies involved in Diamond mining.
SELECT 
    name, `Project Stage`
FROM
    table_1
WHERE
    Commodity LIKE '%Diamond%';

-- 6. Identify the unit of measurement used for 'Nickel' in Table 2.
SELECT DISTINCT
    unit
FROM
    table_2
WHERE
    mined_raw_mat = 'Nickel';

-- 7. List all companies in Table 1 that are in the 'Production' stage.
SELECT 
    *
FROM
    table_1
WHERE
    `Project Stage` LIKE '%Production%';

-- 8. Find the top 3 commodities mined in Zimbabwe based on total production in 2021.
SELECT 
    mined_raw_mat, SUM(year_2021) AS total_production
FROM
    table_2
WHERE
    country = 'Zimbabwe'
GROUP BY mined_raw_mat
ORDER BY total_production DESC
LIMIT 3;

-- 9. Retrieve records where the production of any commodity exceeded 1 million tons in 2022.
SELECT 
    mined_raw_mat, year_2020
FROM
    table_2
WHERE
    year_2020 > 1000000;
    
    
-- 10. List the countries where 'Talc' production decreased between 2018 and 2022.
SELECT 
    country
FROM
    table_2
WHERE
    mined_raw_mat = 'Talc'
        AND year_2018 > year_2022;
        
-- Intermediate Queries

-- 1. Calculate the total revenue generated by all companies mining 'Gold' from 2018 to 2022.
/*Clarification: "In this context, the market capitalization value in Table 1 (column:
'Ticker / Market Capitalization') will be used as a proxy for the company’s potential
revenue. Please assume that market capitalization is directly proportional to the
revenue generated from mining 'Gold'." */
SELECT 
    *
FROM table_1
WHERE commodity = 'Gold';

-- 2. Find the top 5 countries with the highest total production of all commodities combined for 2022.
SELECT 
		country,
		SUM(year_2022) total_production_2022
FROM table_2
GROUP BY country
ORDER BY total_production_2022 DESC
LIMIT 5;

-- 3. Retrieve the names of companies operating in both 'Canada' and 'Peru'.
select *
From table_1
where Location = 'Candada'   And Location = 'Peru';

-- 4. Identify the commodity with the highest average production per country between 2018 and 2022.
SELECT 
    country,
    mined_raw_mat,
    AVG((year_2018 + year_2019 + year_2020 + year_2021 + year_2022) / 5) Average_production
FROM
    table_2
GROUP BY country , mined_raw_mat
ORDER BY Average_production DESC;


-- 5. Write a query to list the top 3 project stages (by count of companies) from Table 1.
select *
from table_1;
-- 6. Find the total production of 'Copper' in countries where the leading company is based in Africa.
-- 7. Retrieve all commodities mined by companies with a market capitalization exceeding $100M.
-- 8. Calculate the year-over-year growth rate for 'Gold' production in Australia.
select *
from table_2
Where country = 'Australia' 
	AND mined_raw_mat = 'Gold';
-- 9. Find all companies involved in the mining of at least 3 different commodities.
SELECT 
    country
FROM
    table_2
GROUP BY country
HAVING COUNT(DISTINCT mined_raw_mat) >= 3;

SELECT Name
FROM table_1
WHERE Commodity LIKE '%,%,%'  -- Select rows with multiple commodities
GROUP BY Name
HAVING COUNT(DISTINCT TRIM(SUBSTRING_INDEX(Commodity, ',', -1))) >= 3;

-- 10. List the countries that consistently mined 'Platinum' every year from 2018 to 2022.
SELECT  country
FROM table_2
WHERE  mined_raw_mat = 'Platinum'
        AND year_2018 > 0
        AND year_2019 > 0
        AND year_2020 > 0
        AND year_2021 > 0
        AND year_2022 > 0

